/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: {
    files: ["./src/**/*.{html,ts,js}"],
    safelist: [
      'ml-3',
      'mb-3',
      'mt-4',
      'hover:bg-primary',
      '!hover:bg-primary',
      'bg-primary',
      'dark:text-white',
      'text-black',
      'dark:bg-neutral-900',
      'dark:border-neutral-700',
      'dark:text-blue-400',
      'dark:text-gray-400',
      'w-12',
      'h-12',
      'min-w-12',
      'min-h-12',
      'rounded-xl',
      'bg-blue-100',
      'text-blue-600',
      'dark:bg-blue-900',
      'text-2xl',
      'w-[280px]',
      'w-[320px]',
      'w-[200px]',
      'w-[160px]',
      'w-[80px]',
      'w-[50px]',
      'icon-[solar--chat-line-outline]',
      'icon-[solar--book-bookmark-linear]',
      'icon-[solar--settings-minimalistic-outline]',
      'icon-[solar--settings-outline]',
      'icon-[solar--list-linear]',
      'icon-[solar--document-add-linear]',
      'icon-[solar--soundwave-circle-linear]',
      'icon-[material-symbols--keyboard-arrow-down-rounded]',
    ],
  },
  plugins: [
    require("@iconify/tailwind4"),
  ],
};
